CREATE TABLE carro (
	id IDENTITY PRIMARY KEY,
	fabricante VARCHAR(50) NOT NULL,
	modelo VARCHAR(50) NOT NULL,
	placa VARCHAR(7) NOT NULL,
	ano SMALLINT NOT NULL,
	valor DECIMAL(24, 8) NOT NULL,
	ativo BOOLEAN NOT NULL
);